ALTER TABLE products DROP CONSTRAINT IF EXISTS id_check;

ALTER TABLE products DROP CONSTRAINT IF EXISTS product_name_check;

ALTER TABLE products DROP CONSTRAINT IF EXISTS stock_count_check;

ALTER TABLE products DROP CONSTRAINT IF EXISTS sku_check;

ALTER TABLE products DROP CONSTRAINT IF EXISTS price_check;